### ISSUE TITLE
Use output filename from input filename

### ISSUE THREAD

**Issue by vallsv** [Unbewohnte/anicons#1]
Hi,

Thanks for code. It looks to work well.

I would like to generate the output filename the following way.
```
> anicons foo/bar.ani
> ls -l
foo/bar-0.ico
foo/bar-1.ico
foo/bar-2.ico
foo/bar-3.ico
```

Also ImageMagic `convert` use the following way to specify an output and generate multi output files.
```
> convert foo.ico foo.png
> ls -l
foo-0.png
foo-1.png
foo-2.png
foo-3.png
```
I also would like to have a way to specify the output.

Would you agree to have such patch?

**Comment by Unbewohnte** [comment]
Sorry for taking so long to respond ! Noticed your comment too late.

I've never thought about saving files in the same specified directory. Thank you for the idea, this way it is a lot easier to work with anicons inside scripts and do heavy-lifting while processing a lot of separate .ani files in the same directory. My implementation didn't allow that, that's for sure.

I've moved from GitHub so you can clone the patched version from [here instead](http://unbewohnte.xyz:3000/Unbewohnte/anicons) with `git clone http://unbewohnte.xyz:3000/Unbewohnte/anicons`.

As for your second request: conversion between .ico and other image formats is **not** what this tool is about. I simply wanted to extract .ico images from .ani files I had, so I made anicons and I think that it's doing its intended job. For conversion - use other tools

**Comment by vallsv** [comment]
Hi, thanks for the patch and the answer.

About png, i only wanted to show how imagemagic was mangling multiple output file names from a single output file name.

I am very happy with the fact the tool handle a single task in simple way. And it's very convinient you have a single source file, without header.

BTW, I saw your personal website, but i was not very enthusiastic to create and send a patch there because it is not using https. Maybe other people like me care about such things.

See you.
